package ar.edu.untdf.clientes.vista;
import ar.edu.untdf.clientes.ClientesApp;
import ar.edu.untdf.clientes.modelo.Cliente;
import ar.edu.untdf.clientes.util.ClienteTableModel;
import ar.edu.untdf.clientes.util.ClientesTableListener;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Matias
 */
public class Clientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        pack();
        ClientesTableListener listener = new ClientesTableListener(this);
        tableClientes.getSelectionModel().addListSelectionListener(listener);
    }

    public JButton getAceptar() {
        return aceptar;
    }

    public void setAceptar(JButton aceptar) {
        this.aceptar = aceptar;
    }

    public JButton getCancelar() {
        return cancelar;
    }

    public void setCancelar(JButton cancelar) {
        this.cancelar = cancelar;
    }

    public JTextField getFieldApellido() {
        return fieldApellido;
    }

    public void setFieldApellido(JTextField fieldApellido) {
        this.fieldApellido = fieldApellido;
    }

    public JTextField getFieldCuit() {
        return fieldCuit;
    }

    public void setFieldCuit(JTextField fieldCuit) {
        this.fieldCuit = fieldCuit;
    }

    public JTextField getFieldNombre() {
        return fieldNombre;
    }

    public void setFieldNombre(JTextField fieldNombre) {
        this.fieldNombre = fieldNombre;
    }

    public JTable getTableClientes() {
        return tableClientes;
    }

    public void setTableClientes(JTable tableClientes) {
        this.tableClientes = tableClientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        jbDirecciones = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbVolver = new javax.swing.JButton();
        jpDatos = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        fieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fieldApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldCuit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();

        tableClientes.setModel(new ar.edu.untdf.clientes.util.ClienteTableModel());
        tableClientes.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tableClientes);

        jbDirecciones.setText("Direcciones");
        jbDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDireccionesActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.setEnabled(false);

        jbVolver.setText("Cerrar Ventana");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        fieldNombre.setEnabled(false);

        jLabel1.setText("Nombre");

        fieldApellido.setEnabled(false);

        jLabel2.setText("Apellido");

        fieldCuit.setEnabled(false);

        jLabel3.setText("Cuit");

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.setEnabled(false);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevo)
                            .addGroup(jpDatosLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(aceptar)
                                .addGap(18, 18, 18)
                                .addComponent(cancelar))))
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(fieldApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldCuit, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevo)
                .addGap(18, 18, 18)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbDirecciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbVolver))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbDirecciones)
                            .addComponent(jbEliminar)
                            .addComponent(jbVolver))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        fieldApellido.setText("");
        fieldApellido.setEnabled(true);
        fieldNombre.setText("");
        fieldNombre.setEnabled(true);
        fieldCuit.setText("");
        fieldCuit.setEnabled(true);
        aceptar.setEnabled(true);
        cancelar.setEnabled(true);
    }//GEN-LAST:event_nuevoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        Cliente c = new Cliente();
        if(!fieldNombre.getText().equals("") && !fieldApellido.getText().equals("") && !fieldCuit.getText().equals("")) {
            try {
                c.setNombre(fieldNombre.getText());
                c.setApellido(fieldApellido.getText());
                c.setCuit((Long.parseLong(fieldCuit.getText())));
                ClientesApp.getClienteC().create(c);
                tableClientes.setModel(new ClienteTableModel());
                fieldNombre.setText("");
                fieldNombre.setEnabled(false);
                fieldApellido.setText("");
                fieldApellido.setEnabled(false);
                fieldCuit.setText("");
                fieldCuit.setEnabled(false);
                aceptar.setEnabled(false);
                cancelar.setEnabled(false);
            }catch(NumberFormatException ex) {
                JOptionPane.showMessageDialog(null,
                    "Cuit no es numérico",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        else
            JOptionPane.showMessageDialog(null,
                    "Complete los campos obligatorios.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        fieldApellido.setText("");
        fieldApellido.setEnabled(false);
        fieldNombre.setText("");
        fieldNombre.setEnabled(false);
        fieldCuit.setText("");
        fieldCuit.setEnabled(false);
        aceptar.setEnabled(false);
        cancelar.setEnabled(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void jbDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDireccionesActionPerformed
        if(tableClientes.getSelectedRow() != -1) {
            Integer fila = tableClientes.getSelectedRow();
            Long id = (Long) tableClientes.getModel().getValueAt(fila, 0);

            Cliente c = (Cliente) ClientesApp.getClienteC().findCliente(id);
            Direcciones d = new Direcciones(c);
            Aplicacion.getApp().addFrame(d,"Direcciones de "+(String) c.getApellido()+" "+(String) c.getNombre());
        }
        else
            JOptionPane.showMessageDialog(null,
                    "No ha seleccionado ningun cliente",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jbDireccionesActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        try {
            this.setSelected(false);
            this.setVisible(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Direcciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField fieldApellido;
    private javax.swing.JTextField fieldCuit;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDirecciones;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbVolver;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JButton nuevo;
    private javax.swing.JTable tableClientes;
    // End of variables declaration//GEN-END:variables
}
