package ar.edu.untdf.clientes.vista;

import ar.edu.untdf.clientes.ClientesApp;
import ar.edu.untdf.clientes.controller.exceptions.NonexistentEntityException;
import ar.edu.untdf.clientes.modelo.Cliente;
import ar.edu.untdf.clientes.modelo.Direccion;
import ar.edu.untdf.clientes.modelo.DireccionTipo;
import ar.edu.untdf.clientes.util.DireccionTableModel;
import ar.edu.untdf.clientes.util.DireccionesTableListener;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro
 */
public class Direcciones extends javax.swing.JInternalFrame {

    private Cliente miCliente;
    private DireccionTableModel modeloTabla;
    /**
     * Creates new form Direcciones
     */
    public Direcciones(Cliente c) {
        super();
        this.miCliente = (Cliente) c;
        modeloTabla = new DireccionTableModel(c);
        initComponents();
        pack();
        jlID.setText(String.valueOf(c.getId()));
        jlNombre.setText(c.getApellido()+" "+c.getNombre());
        DireccionesTableListener listener = new DireccionesTableListener(this);
        jtDirecciones.getSelectionModel().addListSelectionListener(listener);
        jtDirecciones.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsp = new javax.swing.JScrollPane();
        jtDirecciones = new javax.swing.JTable();
        jpDatos = new javax.swing.JPanel();
        jlCalle = new javax.swing.JLabel();
        jtfCalle = new javax.swing.JTextField();
        jlNumero = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jlTipo = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jtfTelefono = new javax.swing.JTextField();
        jcbTipo = new javax.swing.JComboBox();
        jbCancelar = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jbEliminar = new javax.swing.JButton();
        jbVolver = new javax.swing.JButton();

        jsp.setViewportView(jtDirecciones);

        jlCalle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlCalle.setText("Calle");

        jtfCalle.setToolTipText("");
        jtfCalle.setEnabled(false);

        jlNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlNumero.setText("Numero");

        jtfNumero.setEnabled(false);

        jlTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlTipo.setText("Tipo");

        jlTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlTelefono.setText("Telefono");

        jtfTelefono.setEnabled(false);

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TRABAJO", "PERSONAL" }));
        jcbTipo.setEnabled(false);

        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbAceptar.setText("Aceptar");
        jbAceptar.setEnabled(false);
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNuevo)
                .addContainerGap())
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTipo)
                            .addComponent(jlNumero)
                            .addComponent(jlCalle)))
                    .addGroup(jpDatosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jlTelefono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jcbTipo, 0, 231, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpDatosLayout.createSequentialGroup()
                            .addComponent(jbAceptar)
                            .addGap(18, 18, 18)
                            .addComponent(jbCancelar))
                        .addComponent(jtfNumero, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfCalle, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCalle)
                    .addComponent(jtfCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNumero)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTipo)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefono)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("ID:");

        jLabel3.setText("Nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbVolver.setText("Cerrar Ventana");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbVolver))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 174, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbEliminar)
                            .addComponent(jbVolver))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        try {
            this.setSelected(false);
            this.setVisible(false);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Direcciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        jtfCalle.setText("");
        jtfCalle.setEnabled(true);
        jtfNumero.setText("");
        jtfNumero.setEnabled(true);
        jtfTelefono.setText("");
        jtfTelefono.setEnabled(true);
        jcbTipo.setEnabled(true);
        jbAceptar.setEnabled(true);
        jbCancelar.setEnabled(true);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        jtfCalle.setText("");
        jtfCalle.setEnabled(false);
        jtfNumero.setText("");
        jtfNumero.setEnabled(false);
        jtfTelefono.setText("");
        jtfTelefono.setEnabled(false);
        jcbTipo.setEnabled(false);
        jbAceptar.setEnabled(false);
        jbCancelar.setEnabled(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        Direccion d = new Direccion();
        if(!jtfCalle.getText().equals("") && !jtfNumero.getText().equals("") && !jtfTelefono.getText().equals("")) {
            try {
                d.setCalle(jtfCalle.getText());
                d.setNumero(Integer.parseInt(jtfNumero.getText()));
                d.setTelefono(Long.parseLong(jtfTelefono.getText()));
                String tipo = (String) jcbTipo.getSelectedItem();
                if(tipo.equals("TRABAJO"))
                    d.setTipo(DireccionTipo.TRABAJO);
                else if(tipo.equals("PERSONAL"))
                    d.setTipo(DireccionTipo.PERSONAL);
                d.setCliente(miCliente);
                ClientesApp.getDireccionC().create(d);
                modeloTabla = new DireccionTableModel(miCliente);
                jtDirecciones.setModel(modeloTabla);
                jtfCalle.setText("");
                jtfCalle.setEnabled(false);
                jtfNumero.setText("");
                jtfNumero.setEnabled(false);
                jtfTelefono.setText("");
                jtfTelefono.setEnabled(false);
                jcbTipo.setEnabled(false);
                jbAceptar.setEnabled(false);
                jbCancelar.setEnabled(false);
            }catch(NumberFormatException ex) {
                JOptionPane.showMessageDialog(null,
                    "Numero no es numérico",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (jtDirecciones.getSelectedRow() >= 0) {
            modeloTabla.eliminarDireccion(jtDirecciones.getSelectedRow());
            modeloTabla = new DireccionTableModel(miCliente);
            jtDirecciones.setModel(modeloTabla);
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbVolver;
    private javax.swing.JComboBox jcbTipo;
    private javax.swing.JLabel jlCalle;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable jtDirecciones;
    private javax.swing.JTextField jtfCalle;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jbAceptar
     */
    public javax.swing.JButton getJbAceptar() {
        return jbAceptar;
    }

    /**
     * @param jbAceptar the jbAceptar to set
     */
    public void setJbAceptar(javax.swing.JButton jbAceptar) {
        this.jbAceptar = jbAceptar;
    }

    /**
     * @return the jbCancelar
     */
    public javax.swing.JButton getJbCancelar() {
        return jbCancelar;
    }

    /**
     * @param jbCancelar the jbCancelar to set
     */
    public void setJbCancelar(javax.swing.JButton jbCancelar) {
        this.jbCancelar = jbCancelar;
    }

    /**
     * @return the jbNuevo
     */
    public javax.swing.JButton getJbNuevo() {
        return jbNuevo;
    }

    /**
     * @param jbNuevo the jbNuevo to set
     */
    public void setJbNuevo(javax.swing.JButton jbNuevo) {
        this.jbNuevo = jbNuevo;
    }

    /**
     * @return the jlCalle
     */
    public javax.swing.JLabel getJlCalle() {
        return jlCalle;
    }

    /**
     * @param jlCalle the jlCalle to set
     */
    public void setJlCalle(javax.swing.JLabel jlCalle) {
        this.jlCalle = jlCalle;
    }

    /**
     * @return the jlNumero
     */
    public javax.swing.JLabel getJlNumero() {
        return jlNumero;
    }

    /**
     * @param jlNumero the jlNumero to set
     */
    public void setJlNumero(javax.swing.JLabel jlNumero) {
        this.jlNumero = jlNumero;
    }

    /**
     * @return the jlTelefono
     */
    public javax.swing.JLabel getJlTelefono() {
        return jlTelefono;
    }

    /**
     * @param jlTelefono the jlTelefono to set
     */
    public void setJlTelefono(javax.swing.JLabel jlTelefono) {
        this.jlTelefono = jlTelefono;
    }

    /**
     * @return the jlTipo
     */
    public javax.swing.JLabel getJlTipo() {
        return jlTipo;
    }

    /**
     * @param jlTipo the jlTipo to set
     */
    public void setJlTipo(javax.swing.JLabel jlTipo) {
        this.jlTipo = jlTipo;
    }

    /**
     * @return the jpDatos
     */
    public javax.swing.JPanel getJpDatos() {
        return jpDatos;
    }

    /**
     * @param jpDatos the jpDatos to set
     */
    public void setJpDatos(javax.swing.JPanel jpDatos) {
        this.jpDatos = jpDatos;
    }

    /**
     * @return the jsp
     */
    public javax.swing.JScrollPane getJsp() {
        return jsp;
    }

    /**
     * @param jsp the jsp to set
     */
    public void setJsp(javax.swing.JScrollPane jsp) {
        this.jsp = jsp;
    }

    /**
     * @return the jtDirecciones
     */
    public javax.swing.JTable getJtDirecciones() {
        return jtDirecciones;
    }

    /**
     * @param jtDirecciones the jtDirecciones to set
     */
    public void setJtDirecciones(javax.swing.JTable jtDirecciones) {
        this.jtDirecciones = jtDirecciones;
    }

    /**
     * @return the jtfCalle
     */
    public javax.swing.JTextField getJtfCalle() {
        return jtfCalle;
    }

    /**
     * @param jtfCalle the jtfCalle to set
     */
    public void setJtfCalle(javax.swing.JTextField jtfCalle) {
        this.jtfCalle = jtfCalle;
    }

    /**
     * @return the jtfNumero
     */
    public javax.swing.JTextField getJtfNumero() {
        return jtfNumero;
    }

    /**
     * @param jtfNumero the jtfNumero to set
     */
    public void setJtfNumero(javax.swing.JTextField jtfNumero) {
        this.jtfNumero = jtfNumero;
    }

    /**
     * @return the jtfTelefono
     */
    public javax.swing.JTextField getJtfTelefono() {
        return jtfTelefono;
    }

    /**
     * @param jtfTelefono the jtfTelefono to set
     */
    public void setJtfTelefono(javax.swing.JTextField jtfTelefono) {
        this.jtfTelefono = jtfTelefono;
    }

    /**
     * @return the jtfTipo
     */
    public javax.swing.JComboBox getJcbTipo() {
        return jcbTipo;
    }

    /**
     * @param jtfTipo the jtfTipo to set
     */
    public void setJcbTipo(javax.swing.JComboBox jtfTipo) {
        this.jcbTipo = jtfTipo;
    }

    /**
     * @return the miCliente
     */
    public Cliente getMiCliente() {
        return miCliente;
    }

    /**
     * @param miCliente the miCliente to set
     */
    public void setMiCliente(Cliente miCliente) {
        this.miCliente = miCliente;
    }
}
